### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by TManSus** [CodingDaniel1/bs-docs#3]
In the banana shooter documentation, in the step n° 7 of the How to setup your model in unity, in https://bs-docs.readthedocs.io/en/latest/map-editor/import-custom-models.html it says propmt, instead of prompt.
![image](https://github.com/CodingDaniel1/bs-docs/assets/139597815/fec9fd27-a220-4f0f-aa29-97fa61932619)

**Comment by CodingDaniel1** [comment]
Thank you for the correction
